### ISSUE TITLE
Is this still working as of 10/2017?

### ISSUE THREAD

**Issue by drmstwizard** [beije/tumblr-tags#1]
Hi! I have used this script with great success through 8/2017, but I've been encountering problems as of 9/2017-10/2017. Is this still functioning? Thanks!

**Comment by beije** [comment]
Seems to be working.

You can try it here http://rawgit.com/beije/tumblr-tags/master/example/index.html use engineering (which is tumblr's engineering blog).

I have noticed that blogs with with many posts (as in tens of thousands) might end up being blocked because of too many requests.

**Comment by drmstwizard** [comment]
Is there a way to override that? "Tens of thousands of posts" is super
common on the fandom side of Tumblr, and it's why I personally found this
script so useful until I guess I hit the timeout number.

**Comment by beije** [comment]
@drmstwizard without having any large tumblr blog to test against, my best bet would be to decrease the batch size, and increase the batch timeout.

https://github.com/beije/tumblr-tags/blob/a5c8fd0a7040f31dfe5d74793c38c067b79aa429/src/tumblrTags.js#L19-L20
