### ISSUE TITLE
How can I sort the tags form most commonly used to least commonly used?

### ISSUE THREAD

**Issue by shimizurei** [beije/tumblr-tags#3]
I want to see my most commonly tagged items in a formatted way.

**Comment by beije** [comment]
The script returns an array of objects, each object contains the name of the tag and the amount of hits that tag has. You should be able to sort the results with a simple sort function.

```
function sortObjectsByHits(a,b) {
  if (a.hits < b.hits)
    return 1;
  if (a.hits > b.hits)
    return -1;
  return 0;
}

tags.sort(sortObjectsByHits) // Returns a sorted array
```
