### ISSUE TITLE
Tumblr API has been updated since your last commit.

### ISSUE THREAD

**Issue by drmstwizard** [beije/tumblr-tags#4]
I think the reason that timeouts are an issue with your script (as opposed to scripts like https://github.com/alexwlchan/finduntaggedtumblrposts.com or https://github.com/new-xkit/XKit, for your reference) is that you are running Tumblr's old API, which is outdated. Tumblr's new API + API key generator are here: https://www.tumblr.com/docs/en/api/v2... might be worth an overhaul for functionality?

**Comment by beije** [comment]
Since this code is supposed to run on the client/frontend, I don't think it would be wise to leak/support private API keys.
